@echo off
ECHO Launching the browser...
"C:\Program Files\Mozilla Firefox\firefox" http://127.0.0.1:8051/
ECHO Activating the conda environment...
call conda activate
ECHO Launching the program...
python GonioSpec_GUI.py
call conda deactivate